# This dockerfile is used only to simulate a Python interpreter installed on local system
# to perform tests

FROM python:3.11-slim

RUN python3 -m pip install virtualenv

CMD ["tail", "-f", "/dev/null"]