#!/bin/sh

libs_folder=$PWD/libs
staged=$(git diff --name-only --cached)
affected_files=""
affected_projects=""
global_result=0

for file in $staged; do
    if [[ $file == libs* ]]; then        
        if [ -z "$affected_files" ]; then
            affected_files="$PWD/$file"
        else
            affected_files="$affected_files $PWD/$file"
        fi
    fi
done

for file in $affected_files; do
    if [[ "$file" =~ .*\/libs\/[^\/]+ ]]; then
        if [[ "$affected_projects" != *"${BASH_REMATCH[0]}"* ]]; then
            if [[ -z "$affected_projects" ]]; then
                affected_projects="${BASH_REMATCH[0]}"
            else
                affected_projects="$affected_projects ${BASH_REMATCH[0]}"
            fi
        fi
    fi
done

if [ -n "$affected_projects" ]; then
    for dir in $affected_projects; do
        result=$(mvn -f $dir/pom.xml test)
        if  [[ $result -ne 0 ]]; then
            echo Error running tests for $dir
            global_result=1
            break
        fi
    done
fi

exit $global_result