version: "3.9"
services:
  zoo1:
    container_name: zoo1
    image: $ZOOKEEPER_IMG
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    container_name: zoo2
    image: $ZOOKEEPER_IMG
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo3:
    container_name: zoo3
    image: $ZOOKEEPER_IMG
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoonavigator:
    image: $ZOONAVIGATOR_IMG
    container_name: zoonavigator
    restart: always
    ports:
      - 9000:9000/tcp
    environment:
      HTTP_PORT: 9000
      AUTO_CONNECT_CONNECTION_ID: MYZK
      CONNECTION_MYZK_CONN: 'zoo1:2181,zoo2:2182,zoo3:2183'
